
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gem_auction?createDatabseIfNotExist=true
    username: root
    password: madushan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true